/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./src/components/AppFooter.vue')['default']
    BloodTypeCard: typeof import('./src/components/BloodTypeCard.vue')['default']
    BloodTypesSection: typeof import('./src/components/BloodTypesSection.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    HeroSection: typeof import('./src/components/HeroSection.vue')['default']
    HowItWorks: typeof import('./src/components/HowItWorks.vue')['default']
    Navbar: typeof import('./src/components/Navbar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
